In [2]:
import torch

In [3]:
data = [[1, 2], [3, 4]]

my_tensor = torch.tensor(data)
print(my_tensor)

tensor([[1, 2],
        [3, 4]])


In [4]:
shape = (2, 4)

my_zeros = torch.zeros(shape)
print(my_zeros)

my_ones = torch.ones(shape)
print(my_ones)
my_random = torch.rand(shape)
print(my_random)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.6572, 0.0235, 0.6393, 0.2738],
        [0.1271, 0.3517, 0.3366, 0.7237]])


In [5]:
create_from_template = torch.randn_like(my_tensor, dtype=torch.float16)
print(create_from_template)

tensor([[ 0.2747, -0.3804],
        [-0.4495, -1.1113]], dtype=torch.float16)


In [6]:
print(create_from_template.dtype)
print(create_from_template.shape)
print(create_from_template.device)

torch.float16
torch.Size([2, 2])
cpu


In [7]:
# data vs parameters
x_data = torch.rand(10, 3)
x_parameter = torch.rand(10, 3, requires_grad=True)

print(x_data)
print(x_parameter)

tensor([[0.6271, 0.9399, 0.5503],
        [0.3375, 0.1262, 0.1667],
        [0.8619, 0.8958, 0.6416],
        [0.5397, 0.0463, 0.4714],
        [0.1556, 0.6823, 0.3335],
        [0.5255, 0.5643, 0.3084],
        [0.0316, 0.4205, 0.0641],
        [0.6032, 0.2589, 0.4843],
        [0.7429, 0.7912, 0.7772],
        [0.9864, 0.2731, 0.4138]])
tensor([[0.7550, 0.5198, 0.7605],
        [0.8696, 0.5718, 0.6857],
        [0.7388, 0.8649, 0.2779],
        [0.3841, 0.5952, 0.3360],
        [0.2009, 0.5024, 0.3692],
        [0.4332, 0.4941, 0.6358],
        [0.2735, 0.3575, 0.3683],
        [0.6922, 0.6718, 0.4023],
        [0.0584, 0.8292, 0.5063],
        [0.2865, 0.7973, 0.2755]], requires_grad=True)


In [8]:
# Grad 
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

y = a + b
z = y * x

print(z)
print(z.grad_fn)
print(y.grad_fn)
print(a.grad_fn)

tensor(20., grad_fn=<MulBackward0>)
None


In [9]:
# * vs @ for matrix multiplication

a = torch.tensor([[1, 2, 3]])
b = torch.tensor([[20, 30], [40, 50], [2, 3]])

# this calculates: [[1*10, 2*20], [3*30, 4*40]]
#print(a * b)  # element-wise multiplication

# matric multiplication
# m1 columns must match m2 rows
print(a @ b)  # matrix multiplication

tensor([[106, 139]])


In [ ]:
#overall mean

x = torch.tensor([[5., 10., 15], [10.0, 20.0, 30.0]])
#(5 + 10 + 15 + 10 + 20 + 30) / 6 = 15
x.mean()

tensor(15.)

In [ ]:
#mean across columns (5 + 10) / 2 = 7.5, (10 + 20) / 2 = 15, (15 + 30) / 2 = 22.5
print(x.mean(dim=0))
#mean across rows (5 + 10 + 15) / 3 = 10, (10 + 20 + 30) / 3 = 20
print(x.mean(dim=1))

tensor([ 7.5000, 15.0000, 22.5000])
tensor([10., 20.])


In [19]:
x = torch.arange(12).reshape(3, 4)
#tensor([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

# get the third column at index 2
print(x[:, 2])


tensor([ 2,  6, 10])


In [21]:
scores = torch.tensor([
    [10, 0, 5, 20, 1],
    [1, 30, 2,3,4]
])

# get the index of the highest score for each row
print(scores.argmax(dim=1))

# get the index of the highest score for each column
print(scores.argmax(dim=0))

tensor([3, 1])
tensor([0, 1, 0, 0, 1])


In [22]:
# custom selection with torch.Gather()

data = torch.tensor([
    [10, 0, 5, 20, 1],
    [1, 30, 2,3,4],
    [20, 1, 2, 3, 4]
])

indices_to_gather = torch.tensor([[2], [0], [1]])

print(torch.gather(data, dim=1, index=indices_to_gather))

tensor([[5],
        [1],
        [1]])


## Forward Pass

In [ ]:
# ===============forward pass================

#batch of data
N = 10

#each data point has one input feature and one output feature
D_in = 1
D_out = 1

#create input data
x = torch.randn(N, D_in)

#create true targets and add some noise
true_w = torch.tensor([[2.0]])
true_b = torch.tensor([[1.0]])
y_true = x @ true_w + true_b + 0.1 * torch.randn(N, D_out)
#print(y_true)

#initialize random weights
w = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(D_out, requires_grad=True)

print(w)
print(b)

y_hat = x @ w + b
print(f"predicted y: {y_hat} \ntrue y: {y_true}")

tensor([[1.2778]], requires_grad=True)
tensor([0.6137], requires_grad=True)
predicted y: tensor([[-1.0891],
        [ 0.4056],
        [-1.1055],
        [ 2.7175],
        [ 0.6880],
        [-1.2639],
        [-0.5327],
        [ 0.3429],
        [-0.7641],
        [-0.9744]], grad_fn=<AddBackward0>) 
true y: tensor([[-1.8442],
        [ 0.4821],
        [-1.8831],
        [ 4.2051],
        [ 1.1674],
        [-2.0388],
        [-0.7062],
        [ 0.5064],
        [-1.2695],
        [-1.4482]])


In [33]:
# mean squared error loss
loss = torch.mean((y_hat - y_true) ** 2)
print(f"loss: {loss}") # this is the value we want to minimize

loss.backward()

print(f"gradient of w: {w.grad}")
print(f"gradient of b: {b.grad}")

loss: 0.47608861327171326
gradient of w: tensor([[-1.3821]])
gradient of b: tensor([0.2506])
