In [2]:
import torch

In [3]:
data = [[1, 2], [3, 4]]
data2 = torch.tensor(1)
my_tensor = torch.tensor(data)
print(my_tensor)
print(data2)

tensor([[1, 2],
        [3, 4]])
tensor(1)


In [4]:
shape = (2, 4)

my_zeros = torch.zeros(shape)
print(my_zeros)

my_ones = torch.ones(shape)
print(my_ones)
my_random = torch.rand(shape)
print(my_random)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.3224, 0.2036, 0.4287, 0.0665],
        [0.9302, 0.8056, 0.3334, 0.6488]])


In [5]:
create_from_template = torch.randn_like(my_tensor, dtype=torch.float16)
print(create_from_template)

tensor([[-0.3574,  0.1700],
        [ 0.4417, -0.7188]], dtype=torch.float16)


In [6]:
print(create_from_template.dtype)
print(create_from_template.shape)
print(create_from_template.device)

torch.float16
torch.Size([2, 2])
cpu


In [7]:
# data vs parameters
x_data = torch.rand(10, 3)
x_parameter = torch.rand(10, 3, requires_grad=True)

print(x_data)
print(x_parameter)

tensor([[0.6584, 0.6015, 0.1092],
        [0.8573, 0.0574, 0.1084],
        [0.0643, 0.0448, 0.8662],
        [0.9637, 0.2939, 0.7667],
        [0.2701, 0.6756, 0.9432],
        [0.9314, 0.4795, 0.2779],
        [0.2391, 0.1837, 0.4352],
        [0.2911, 0.0274, 0.7829],
        [0.9502, 0.2331, 0.3730],
        [0.4210, 0.6733, 0.9727]])
tensor([[0.6137, 0.6434, 0.5111],
        [0.0163, 0.1514, 0.3989],
        [0.2027, 0.1456, 0.1168],
        [0.1570, 0.5725, 0.6996],
        [0.0855, 0.1612, 0.7442],
        [0.7486, 0.0359, 0.4126],
        [0.8480, 0.8970, 0.6173],
        [0.5838, 0.8340, 0.1971],
        [0.1764, 0.7431, 0.9073],
        [0.4652, 0.6857, 0.4487]], requires_grad=True)


In [8]:
# Grad 
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

y = a + b
z = y * x

print(z)
print(z.grad_fn)
print(y.grad_fn)
print(a.grad_fn)

tensor(20., grad_fn=<MulBackward0>)
None


In [9]:
# * vs @ for matrix multiplication

a = torch.tensor([[1, 2, 3]])
b = torch.tensor([[20, 30], [40, 50], [2, 3]])

# this calculates: [[1*10, 2*20], [3*30, 4*40]]
#print(a * b)  # element-wise multiplication

# matric multiplication
# m1 columns must match m2 rows
print(a @ b)  # matrix multiplication

tensor([[106, 139]])


In [10]:
#overall mean

x = torch.tensor([[5., 10., 15], [10.0, 20.0, 30.0]])
#(5 + 10 + 15 + 10 + 20 + 30) / 6 = 15
x.mean()

tensor(15.)

In [11]:
#mean across columns (5 + 10) / 2 = 7.5, (10 + 20) / 2 = 15, (15 + 30) / 2 = 22.5
print(x.mean(dim=0))
#mean across rows (5 + 10 + 15) / 3 = 10, (10 + 20 + 30) / 3 = 20
print(x.mean(dim=1))

tensor([ 7.5000, 15.0000, 22.5000])
tensor([10., 20.])


In [12]:
x = torch.arange(12).reshape(3, 4)
#tensor([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

# get the third column at index 2
print(x[:, 2])


tensor([ 2,  6, 10])


In [13]:
scores = torch.tensor([
    [10, 0, 5, 20, 1],
    [1, 30, 2,3,4]
])

# get the index of the highest score for each row
print(scores.argmax(dim=1))

# get the index of the highest score for each column
print(scores.argmax(dim=0))

tensor([3, 1])
tensor([0, 1, 0, 0, 1])


In [14]:
# custom selection with torch.Gather()

data = torch.tensor([
    [10, 0, 5, 20, 1],
    [1, 30, 2,3,4],
    [20, 1, 2, 3, 4]
])

indices_to_gather = torch.tensor([[2], [0], [1]])

print(torch.gather(data, dim=1, index=indices_to_gather))

tensor([[5],
        [1],
        [1]])


## Forward Pass

In [15]:
# ===============forward pass================

#batch of data
N = 10

#each data point has one input feature and one output feature
D_in = 1
D_out = 1

#create input data
x = torch.randn(N, D_in)

#create true targets and add some noise
true_w = torch.tensor([[2.0]])
true_b = torch.tensor([[1.0]])
y_true = x @ true_w + true_b + 0.1 * torch.randn(N, D_out)
#print(y_true)

#initialize random weights
w = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(D_out, requires_grad=True)

print(w)
print(b)

y_hat = x @ w + b
print(f"predicted y: {y_hat} \ntrue y: {y_true}")

tensor([[-0.3108]], requires_grad=True)
tensor([-0.3791], requires_grad=True)
predicted y: tensor([[-0.5909],
        [-0.4435],
        [-0.0623],
        [-0.4985],
        [-0.6175],
        [ 0.1002],
        [-0.0712],
        [-0.3325],
        [-0.5147],
        [ 0.0031]], grad_fn=<AddBackward0>) 
true y: tensor([[ 2.2743],
        [ 1.4076],
        [-1.0254],
        [ 1.7804],
        [ 2.4579],
        [-1.8995],
        [-0.8730],
        [ 0.7746],
        [ 1.7521],
        [-1.6058]])


In [16]:
# mean squared error loss
loss = torch.mean((y_hat - y_true) ** 2)
print(f"loss: {loss}") # this is the value we want to minimize

loss.backward()

print(f"gradient of w: {w.grad}")
print(f"gradient of b: {b.grad}")

loss: 4.080869197845459
gradient of w: tensor([[-2.6467]])
gradient of b: tensor([-1.6142])


In [ ]:
learning_rate = 0.01
epochs = 100

w = torch.randn(D_in, D_out, requires_grad=True)

b = torch.randn(D_out, requires_grad=True)
for epoch in range(epochs):
    # forward pass
    y_hat = x @ w + b
    loss = torch.mean((y_hat - y_true) ** 2)

    # backward pass
    loss.backward()

    # update weights using gradient descent
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        # zero the gradients after updating
        w.grad.zero_()
        b.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

2
Epoch 0, Loss: 4.671706199645996
Epoch 10, Loss: 3.627023696899414
Epoch 20, Loss: 2.8250677585601807
Epoch 30, Loss: 2.206383228302002
Epoch 40, Loss: 1.7271093130111694
Epoch 50, Loss: 1.354562520980835
Epoch 60, Loss: 1.064163088798523
Epoch 70, Loss: 0.8372783660888672
Epoch 80, Loss: 0.659686803817749
Epoch 90, Loss: 0.5204693078994751
