In [28]:
import torch

In [29]:
rt = torch.rand(3,4)
print(rt)
print(rt.ndim)
rt.shape

tensor([[0.4744, 0.6939, 0.8513, 0.9443],
        [0.3133, 0.8819, 0.1719, 0.0395],
        [0.9970, 0.2817, 0.8291, 0.2743]])
2


torch.Size([3, 4])

In [30]:
rt2 = torch.rand(2, 5, 2,3)
print(rt2)
print(rt2.ndim)
rt2.shape

tensor([[[[0.2644, 0.6181, 0.8091],
          [0.2427, 0.8994, 0.4400]],

         [[0.3905, 0.9962, 0.6587],
          [0.4882, 0.6608, 0.0716]],

         [[0.3019, 0.4520, 0.3899],
          [0.1393, 0.6543, 0.8676]],

         [[0.0595, 0.7769, 0.2121],
          [0.3536, 0.7320, 0.4062]],

         [[0.7638, 0.0821, 0.9634],
          [0.2759, 0.6071, 0.4818]]],


        [[[0.4422, 0.9355, 0.5966],
          [0.4237, 0.7936, 0.8737]],

         [[0.9758, 0.7613, 0.5234],
          [0.2960, 0.1093, 0.3084]],

         [[0.6945, 0.7377, 0.2968],
          [0.5034, 0.1894, 0.5493]],

         [[0.7404, 0.8231, 0.6730],
          [0.8391, 0.7728, 0.1701]],

         [[0.1154, 0.0036, 0.6285],
          [0.4643, 0.9793, 0.1469]]]])
4


torch.Size([2, 5, 2, 3])

In [31]:
img = torch.rand(3, 224, 224)
print(img)
print(img.ndim) 
print(img.shape)

tensor([[[0.4359, 0.0025, 0.8864,  ..., 0.8126, 0.7331, 0.8119],
         [0.2192, 0.5168, 0.6634,  ..., 0.2348, 0.5836, 0.5830],
         [0.8598, 0.3464, 0.4438,  ..., 0.5900, 0.5608, 0.6514],
         ...,
         [0.1276, 0.5755, 0.2745,  ..., 0.8315, 0.2367, 0.9966],
         [0.6861, 0.1097, 0.9718,  ..., 0.8174, 0.3304, 0.2410],
         [0.6110, 0.7772, 0.8466,  ..., 0.9229, 0.7747, 0.9323]],

        [[0.3904, 0.8475, 0.8123,  ..., 0.7672, 0.3636, 0.6084],
         [0.5464, 0.5400, 0.6799,  ..., 0.8897, 0.8553, 0.8542],
         [0.7590, 0.8208, 0.9815,  ..., 0.3959, 0.0063, 0.9465],
         ...,
         [0.4001, 0.0896, 0.8095,  ..., 0.6666, 0.5217, 0.1819],
         [0.8310, 0.9020, 0.6712,  ..., 0.3595, 0.1989, 0.1214],
         [0.4220, 0.5960, 0.3686,  ..., 0.8784, 0.1720, 0.0990]],

        [[0.3091, 0.6172, 0.7964,  ..., 0.2550, 0.2137, 0.7030],
         [0.9178, 0.1122, 0.1961,  ..., 0.1729, 0.5597, 0.8817],
         [0.6265, 0.8791, 0.2452,  ..., 0.3282, 0.2567, 0.

In [ ]:
torch.__version__


one_to_ten = torch.arange(1, 10, 2)
print(one_to_ten)


tensor([1, 3, 5, 7, 9])


In [47]:
ten_zeros = torch.zeros_like(one_to_ten)
print(ten_zeros)
copy_tensor = torch.randn_like(one_to_ten.float())
print(copy_tensor)
print(one_to_ten.clone())
print(torch.randint_like(one_to_ten, low=0, high=10))

tensor([0, 0, 0, 0, 0])
tensor([ 1.5858,  0.4646,  0.2855,  1.8288, -0.1826])
tensor([1, 3, 5, 7, 9])
tensor([4, 1, 1, 2, 1])


In [52]:
tensor_add = torch.tensor([1, 2, 3]) + torch.tensor([10, 20, 30])
print(tensor_add)

tensor_mul = torch.tensor([1, 2, 3]) * torch.tensor([10, 20, 30])
print(tensor_mul)

tensor_sub = torch.tensor([1, 2, 3]) - torch.tensor([10, 20, 30])
print(tensor_sub)

tensor([11, 22, 33])
tensor([10, 40, 90])
tensor([ -9, -18, -27])


In [ ]:
#matrix multiplication

#rules: 1. inner dimensions must match
#       2. the resulting shape is the outer dimensions


tensor1 = torch.rand(2, 3) # first dimension is the number of rows, second dimension is the number of columns
tensor2 = torch.rand(3, 4)
tensor3 = torch.rand(4, 5)

print(tensor1 @ tensor2) #shape (2, 4)
print("----")
print(tensor2 @ tensor3) #shape (3, 5)
print("----")
print(tensor1 @ tensor2 @ tensor3) #shape (2, 5) because the inner dimensions (4) match and the resulting shape is the outer dimensions (2, 5)

tensor([[0.5281, 0.2302, 1.0323, 0.4242],
        [0.8020, 0.3143, 0.6517, 0.4708]])
----
tensor([[0.3514, 1.1486, 0.6098, 0.8627, 1.0440],
        [0.2129, 0.5765, 0.8574, 0.5316, 0.6074],
        [0.2863, 1.0053, 1.0694, 0.9676, 1.0720]])
----
tensor([[0.4598, 1.4958, 1.0736, 1.2070, 1.4241],
        [0.4098, 1.3692, 1.1810, 1.1900, 1.3664]])


In [61]:
# transpose

tensor_1 = torch.rand(3, 4)
print(tensor_1)
tensor_2 = torch.rand(3, 4) # this cannot be matrix multiplied with tensor_1 because the inner dimensions do not match
print(tensor_2)

tensor_2 = tensor_2.T # transpose of tensor_2, now it has shape (4, 3) and can be matrix multiplied with tensor_1

print(tensor_2)
print(tensor_1 @ tensor_2) # shape (3, 3) because the inner dimensions (4) match and the resulting shape is the outer dimensions (3, 3)

tensor([[0.8247, 0.0839, 0.9621, 0.7395],
        [0.2487, 0.5757, 0.5880, 0.6546],
        [0.0133, 0.2772, 0.6780, 0.1307]])
tensor([[0.5251, 0.2091, 0.2625, 0.7893],
        [0.0182, 0.6668, 0.9651, 0.1106],
        [0.6290, 0.8895, 0.9340, 0.1956]])
tensor([[0.5251, 0.0182, 0.6290],
        [0.2091, 0.6668, 0.8895],
        [0.2625, 0.9651, 0.9340],
        [0.7893, 0.1106, 0.1956]])
tensor([[1.2868, 1.0811, 1.6366],
        [0.9220, 1.0282, 1.3457],
        [0.3461, 0.8539, 0.9138]])


In [71]:
tensor = torch.arange(1, 10, 2)
print(tensor)
print(tensor.min())
print(tensor.max())
print(tensor.float().mean())
tensor.type(torch.float)
print(tensor.sum())
print(tensor.argmax())
print(tensor.argmin())

tensor([1, 3, 5, 7, 9])
tensor(1)
tensor(9)
tensor(5.)
tensor(25)
tensor(4)
tensor(0)


In [ ]:
x = torch.arange(1, 10)
print(x, x.shape)
z = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(z, z.shape)
# add a dimension to x
x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)
x_view = x.view(1, 9) # view is similar to reshape but it does not copy the data, it just changes the shape of the tensor
print(x_view, x_view.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])


In [85]:
# stacking tensors
x_stacked = torch.stack([x, x, x], dim=0) # stack along the first dimension
print(x_stacked, x_stacked.shape)
x_stacked = torch.stack([x, x, x], dim=1) # stack along the second dimension
print(x_stacked, x_stacked.shape)
print(x.reshape(9, 1))

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([3, 9])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]]) torch.Size([9, 3])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
